### ISSUE TITLE
False positive on interface method

### ISSUE THREAD

**Issue by e-dard** [dominikh/go-unused#51] opened 2017-01-09 18:06 UTC
Hi, this one is a little complicated but it has been flagged on a private code-base of ours. I've recreated a version of it below:

```go
package main

import "fmt"

type T struct {
	I interface {
		Foo()
	}
}

func (r *T) f() {
	a := t{I: r.I}
	a.f()
}

type t struct {
	I interface {
		Foo()
	}
}

func (r *t) f() {
	r.I.Foo()
}

type Fooer struct{}

func (Fooer) Foo() { fmt.Println("hello") }

func main() {
	a := T{I: Fooer{}}
	a.f()
}
```

```
⇒  go run main.go
hello

⇒  unused .
/Users/edd/Development/golang/src/github.com/e-dard/scratch/unused/main.go:7:3: func Foo is unused (U1000)
```

So it thinks that `T.I.Foo` is unused, but it's not, because it's used via the interface `I` being assigned to `t`.

**Comment by dominikh** [comment] 2017-01-09 18:12
Thanks for the report. This might be a duplicate of #40, or at least related to it. Will need to investigate.

**Comment by dominikh** [comment] 2019-04-10 20:21
Fixed.

**Closed as completed by dominikh** 2019-04-10 20:21 UTC
Labels: false-positive
