### ISSUE TITLE
False positives in some cases

### ISSUE THREAD

**Issue by calmh** [dominikh/go-unused#15] opened 2016-03-14 21:27 UTC
I'm getting a false positive in one of my packages. I tried to quickly make a small reproduction of it but failed, so I'm not sure what relationship exactly triggers it. However,

```
$ go get github.com/syncthing/syncthing
$ cd $GOPATH/src/github.com/syncthing/syncthing/lib/model
$ unused .
/Users/jb/src/github.com/syncthing/syncthing/lib/model/folderstate.go:83:24: getState is unused
/Users/jb/src/github.com/syncthing/syncthing/lib/model/folderstate.go:115:24: clearError is unused
/Users/jb/src/github.com/syncthing/syncthing/lib/model/model.go:306:7: remoteAddrer is unused
```

Remove the `getState()` method and:

```
$ go build
# github.com/syncthing/syncthing/lib/model
./model.go:167: cannot use p (type *rwFolder) as type service in assignment:
    *rwFolder does not implement service (missing getState method)
./model.go:238: cannot use s (type *roFolder) as type service in assignment:
    *roFolder does not implement service (missing getState method)
```

The type gets embedded and then passed through an interface, but that alone doesn't seem enough to trigger it when I tried reproducing in a smaller case...

**Comment by dominikh** [comment] 2016-03-14 21:41
Can you check if this is a duplicate of #7?

**Comment by dominikh** [comment] 2016-03-14 21:46
That is, does your case look like this minimal example?

```
package pkg

type I interface {
    f1()
    f2()
}

type t1 struct{}
type T2 struct{ t1 }

func (t1) f1() {}
func (T2) f2() {}

func Fn() {
    var v T2
    _ = v.t1
}
```

**Comment by calmh** [comment] 2016-03-14 22:24
It sounds very similar to #7, yes. The type with `getState` gets embedded and provides part of an interface but not all of it.

**Comment by dominikh** [comment] 2016-03-14 22:30
Alright. I'll close this issue in favour of #7 then. I should have a fix ready soonish.

**Closed as completed by dominikh** 2016-03-14 22:30 UTC
Labels: duplicate, false-positive
